// <auto-generated />
namespace FPT_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditTraineeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTraineeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202110141446050_EditTraineeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
